const studentGrades = [
  {
    quizName: 'Science Quiz',
    dateOfQuiz: '2020-07-06',
    quizSubject: 'Science',
    numOfQuestions: 10,
    correctAnswers: 7,
    incorrectAnswers: 2,
    teacherId: 5,
    studentId: 1,
    subjectId: 3,
    ticketTemplateId: 1
  },
  {
    quizName: 'Science Quiz',
    dateOfQuiz: '2020-07-06',
    quizSubject: 'Science',
    numOfQuestions: 10,
    correctAnswers: 10,
    incorrectAnswers: 0,
    teacherId: 5,
    studentId: 2,
    subjectId: 3,
    ticketTemplateId: 1
  },
  {
    quizName: 'Science Quiz',
    dateOfQuiz: '2020-07-06',
    quizSubject: 'Science',
    numOfQuestions: 10,
    correctAnswers: 5,
    incorrectAnswers: 5,
    teacherId: 5,
    studentId: 8,
    subjectId: 3,
    ticketTemplateId: 1
  },
  {
    quizName: 'Science Quiz',
    dateOfQuiz: '2020-07-06',
    quizSubject: 'Science',
    numOfQuestions: 10,
    correctAnswers: 5,
    incorrectAnswers: 0,
    teacherId: 5,
    studentId: 10,
    subjectId: 3,
    ticketTemplateId: 1
  },
  {
    quizName: 'Science Quiz',
    dateOfQuiz: '2020-07-06',
    quizSubject: 'Science',
    numOfQuestions: 10,
    correctAnswers: 10,
    incorrectAnswers: 0,
    teacherId: 5,
    studentId: 15,
    subjectId: 3,
    ticketTemplateId: 1
  },
  {
    quizName: 'Math Quiz',
    dateOfQuiz: '2020-07-08',
    quizSubject: 'Math',
    numOfQuestions: 10,
    correctAnswers: 10,
    incorrectAnswers: 0,
    teacherId: 2,
    studentId: 6,
    subjectId: 2,
    ticketTemplateId: 2
  },
  {
    quizName: 'Math Quiz',
    dateOfQuiz: '2020-07-08',
    quizSubject: 'Math',
    numOfQuestions: 10,
    correctAnswers: 9,
    incorrectAnswers: 1,
    teacherId: 2,
    studentId: 7,
    subjectId: 2,
    ticketTemplateId: 2
  },
  {
    quizName: 'Math Quiz',
    dateOfQuiz: '2020-07-08',
    quizSubject: 'Math',
    numOfQuestions: 10,
    correctAnswers: 8,
    incorrectAnswers: 1,
    teacherId: 2,
    studentId: 9,
    subjectId: 2,
    ticketTemplateId: 2
  },
  {
    quizName: 'Math Quiz',
    dateOfQuiz: '2020-07-08',
    quizSubject: 'Math',
    numOfQuestions: 10,
    correctAnswers: 9,
    incorrectAnswers: 0,
    teacherId: 2,
    studentId: 13,
    subjectId: 2,
    ticketTemplateId: 2
  },
  {
    quizName: 'Math Quiz',
    dateOfQuiz: '2020-07-08',
    quizSubject: 'Math',
    numOfQuestions: 10,
    correctAnswers: 10,
    incorrectAnswers: 0,
    teacherId: 2,
    studentId: 14,
    subjectId: 2,
    ticketTemplateId: 2
  },
  {
    quizName: 'English Quiz',
    dateOfQuiz: '2020-07-08',
    quizSubject: 'English',
    numOfQuestions: 10,
    correctAnswers: 7,
    incorrectAnswers: 2,
    teacherId: 1,
    studentId: 3,
    subjectId: 5,
    ticketTemplateId: 4
  },
  {
    quizName: 'English Quiz',
    dateOfQuiz: '2020-07-08',
    quizSubject: 'English',
    numOfQuestions: 10,
    correctAnswers: 9,
    incorrectAnswers: 0,
    teacherId: 1,
    studentId: 4,
    subjectId: 5,
    ticketTemplateId: 4
  },
  {
    quizName: 'English Quiz',
    dateOfQuiz: '2020-07-08',
    quizSubject: 'English',
    numOfQuestions: 10,
    correctAnswers: 10,
    incorrectAnswers: 0,
    teacherId: 1,
    studentId: 11,
    subjectId: 5,
    ticketTemplateId: 4
  },
  {
    quizName: 'English Quiz',
    dateOfQuiz: '2020-07-08',
    quizSubject: 'English',
    numOfQuestions: 10,
    correctAnswers: 7,
    incorrectAnswers: 3,
    teacherId: 1,
    studentId: 12,
    subjectId: 5,
    ticketTemplateId: 4
  },
  {
    quizName: 'English Quiz',
    dateOfQuiz: '2020-07-08',
    quizSubject: 'English',
    numOfQuestions: 10,
    correctAnswers: 8,
    incorrectAnswers: 1,
    teacherId: 1,
    studentId: 16,
    subjectId: 5,
    ticketTemplateId: 4
  }
]

module.exports = studentGrades
